spring.application.name=Spring_Caching_Redis

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.datasource.url=jdbc:postgresql://localhost:5432/concurrency
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=root
spring.datasource.username=postgres

#redis-config

#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

weatherApi.base.url = https://api.openweathermap.org/data/2.5/weather
#api key of openweather

API_KEY=${Weather_API_KEY}